### ISSUE TITLE
Support for macOS / Adium

### ISSUE THREAD

**Issue by dprandzioch** [EionRobb/purple-rocketchat#5]
Hey, since Adium uses libpurple internally, is there any know way to get the RocketChat plugin working on macOS? I'm going nuts with that wrapped web-app :-)

Thanks in advance

**Comment by EionRobb** [comment]
Technically, yes!  Unfortunately it's not automagic, you need to make an Adium plugin that loads the libpurple plugin, eg https://github.com/tripplet/skypeweb4adium

The other option (but may induce eye-tearing-out due to the less-than pretty GTK on OSX situation) is using Homebrew or Macports to run Pidgin on OSX, and build the Rocket.Chat plugin with that
